-- MySQL Script generated by MySQL Workbench
-- Mon Oct 29 21:01:55 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema skillancer
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `skillancer` ;

-- -----------------------------------------------------
-- Schema skillancer
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `skillancer` DEFAULT CHARACTER SET utf8 ;
USE `skillancer` ;

-- -----------------------------------------------------
-- Table `skillancer`.`Freelancer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `skillancer`.`Freelancer` ;

CREATE TABLE IF NOT EXISTS `skillancer`.`Freelancer` (
  `idFreelancer` INT NOT NULL,
  `Nome_freelancer` VARCHAR(45) NOT NULL,
  `Sobrenome_freelancer` VARCHAR(45) NOT NULL,
  `Projetos` VARCHAR(45) NULL,
  `CPF` VARCHAR(45) NULL,
  `CNPJ` VARCHAR(45) NULL,
  `Username` VARCHAR(45) NOT NULL,
  `Email_freelancer` VARCHAR(45) NOT NULL,
  `Estado` VARCHAR(45) NOT NULL,
  `Pais` VARCHAR(45) NOT NULL,
  `Telefone` INT NOT NULL,
  PRIMARY KEY (`idFreelancer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `skillancer`.`Freelancer_servico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `skillancer`.`Freelancer_servico` ;

CREATE TABLE IF NOT EXISTS `skillancer`.`Freelancer_servico` (
  `idFreelancer_servico` INT NOT NULL,
  `nota_geral` VARCHAR(45) NOT NULL,
  `qtd_vendas` VARCHAR(45) NOT NULL,
  `Freelancer_idFreelancer` INT NOT NULL,
  PRIMARY KEY (`idFreelancer_servico`),
  INDEX `fk_Freelancer_servico_Freelancer1_idx` (`Freelancer_idFreelancer` ASC) VISIBLE,
  CONSTRAINT `fk_Freelancer_servico_Freelancer1`
    FOREIGN KEY (`Freelancer_idFreelancer`)
    REFERENCES `skillancer`.`Freelancer` (`idFreelancer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `skillancer`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `skillancer`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `skillancer`.`Cliente` (
  `idCliente` INT NOT NULL,
  `Nome_cliente` VARCHAR(45) NOT NULL,
  `Sobrenome_cliente` VARCHAR(45) NOT NULL,
  `Telefone_cliente` INT NULL,
  `CPF` INT NULL,
  `CNPJ` INT NULL,
  `Username_cliente` VARCHAR(45) NOT NULL,
  `Email_cliente` VARCHAR(45) NOT NULL,
  `Pais_cliente` VARCHAR(45) NOT NULL,
  `Estado_cliente` VARCHAR(45) NOT NULL,
  `Freelancer_servico_idFreelancer_servico` INT NOT NULL,
  PRIMARY KEY (`idCliente`),
  INDEX `fk_Cliente_Freelancer_servico1_idx` (`Freelancer_servico_idFreelancer_servico` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_Freelancer_servico1`
    FOREIGN KEY (`Freelancer_servico_idFreelancer_servico`)
    REFERENCES `skillancer`.`Freelancer_servico` (`idFreelancer_servico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `skillancer`.`Metodo_pagamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `skillancer`.`Metodo_pagamento` ;

CREATE TABLE IF NOT EXISTS `skillancer`.`Metodo_pagamento` (
  `idPagamento` INT NOT NULL,
  `Cartao` INT NULL,
  `Deposito` VARCHAR(45) NULL,
  `Boleto` VARCHAR(45) NULL,
  PRIMARY KEY (`idPagamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `skillancer`.`Projeto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `skillancer`.`Projeto` ;

CREATE TABLE IF NOT EXISTS `skillancer`.`Projeto` (
  `idProjeto` INT NOT NULL,
  `Nome_projeto` VARCHAR(45) NOT NULL,
  `Categoria` VARCHAR(45) NOT NULL,
  `Nome_cliente` VARCHAR(45) NOT NULL,
  `Freelancer_idFreelancer` INT NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  `Metodo_pagamento_idPagamento` INT NOT NULL,
  PRIMARY KEY (`idProjeto`),
  INDEX `fk_Projeto_Freelancer_idx` (`Freelancer_idFreelancer` ASC) VISIBLE,
  INDEX `fk_Projeto_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  INDEX `fk_Projeto_Metodo_pagamento1_idx` (`Metodo_pagamento_idPagamento` ASC) VISIBLE,
  CONSTRAINT `fk_Projeto_Freelancer`
    FOREIGN KEY (`Freelancer_idFreelancer`)
    REFERENCES `skillancer`.`Freelancer` (`idFreelancer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Projeto_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `skillancer`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Projeto_Metodo_pagamento1`
    FOREIGN KEY (`Metodo_pagamento_idPagamento`)
    REFERENCES `skillancer`.`Metodo_pagamento` (`idPagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
